import turtle as t
def draw_circle():
    t.fillcolor('yellow')
    t.begin_fill()
    t.circle(100)
    t.end_fill()
  #  
    t.left(90)
    t.penup()
    t.forward(75)
    t.pendown()
    t.right(90)
    t.fillcolor('pink')
    t.begin_fill()
    t.circle(15)
    t.end_fill()

 #   
    t.penup()
    t.goto(-40,60)
    t.right(90)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.circle(40,180)
    t.end_fill()

    t.penup()
    t.goto(100,110)
    t.left(90)
    t.forward(50)
    t.pendown()
    t.left(180)
    t.fillcolor('beige')
    t.begin_fill()
    t.circle(20)
    t.end_fill()
   
    t.penup()
    t.goto(-100,110)
    t.forward(50)
    t.pendown()
    t.fillcolor('beige')
    t.begin_fill()
    t.circle(20)
    t.end_fill()
    
    
    t.penup()
    t.goto(-47,117)
    t.pendown()
    t.fillcolor('black')
    t.begin_fill()
    t.circle(10)
    t.end_fill()

    t.penup()
    t.goto(53,117)
    t.pendown()
    t.fillcolor('black')
    t.begin_fill()
    t.circle(10)
    t.end_fill()

    t.penup()
    t.goto(0,80)
    t.fillcolor('black')
    t.begin_fill()
    t.circle(5)
    t.end_fill()

    t.right(90)
    t.goto(-30,60)
    t.fillcolor('red')
    t.begin_fill()
    t.circle(30,180)
    t.end_fill()

    

def main():
    #t.hideturtle()
    t.speed(20)
    draw_circle() 
    t.home()
    t.penup()
    t.goto(-100,-50)
    t.pensize(1)
    t.pendown()
    t.write("አደጋ አለው!!!")
    t.done()
main()